blank_issues_enabled: false
contact_links:
  - name: "💬 GitHub Discussions"
    url: https://github.com/snowztech/barecms/discussions
    about: "Ask questions and discuss BareCMS with the community"
  - name: "📚 Documentation"
    url: https://github.com/snowztech/barecms/blob/main/README.md
    about: "Check documentation and guides"