name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Go Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: UI dependencies
        run: |
          cd ui
          npm install

      - name: UI Lint
        run: |
          cd ui
          npm run lint

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile Build
        run: docker build .
