name: CI BareCMS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4" # Use your desired Go version

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Go Lint (go vet)
        run: go vet ./...

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

      - name: Go Lint (golangci-lint)
        run: $(go env GOPATH)/bin/golangci-lint run ./... --timeout 5m

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install UI dependencies
        run: |
          cd ui
          npm install

      - name: UI Lint
        run: |
          cd ui
          npm run lint

      - name: Validate Dockerfile Build
        run: docker build .
